version: 1.0
Resources:
  -TargetService:
    Type: AWS::ECS::Service
    Properties:
      TaskDefinition:
      LoadBalancerInfo:
        ContainerName: "2073291_processPension"
        ContainerPort: "8084"
      PlatformVersion: "Latest"
